name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend 